### ISSUE TITLE
Admin > Consultations list - "View consultation" link gives 404

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto#148] opened 2016-12-13 09:56 UTC

**Comment by danguita** [comment] 2016-12-13 10:04
Picking up this one 👀

**Comment by danguita** [comment] 2016-12-13 10:13
Can't reproduce it in my environment 😕 

Any Active consultations can be accessed through a new window for me. Drafts can't because we need to deal with Admins behaving like Users in some cases as part of https://github.com/PopulateTools/gobierto-dev/issues/127. Could I be missing something else?

![screen shot 2016-12-13 at 11 08 23 am](https://cloud.githubusercontent.com/assets/126392/21136157/c3e9a156-c124-11e6-8e27-9a073431fc02.jpg)

⬇️ 

![screen shot 2016-12-13 at 11 08 48 am](https://cloud.githubusercontent.com/assets/126392/21136164/c97c5352-c124-11e6-801a-0c04e930e41d.jpg)

**Comment by furilo** [comment] 2016-12-13 10:29
OK, I just see that it's adding another "madrid" to the subdomain. http://madrid.madrid.gobierto.dev/consultas_presupuestos/321127170

If this don't happen in staging/production, I don't care about the error (will have to do with my not-docker installation)

**Comment by danguita** [comment] 2016-12-13 10:36
I see, so it seems to be related to your environment set up. Let me know if I can help on that! Are you OK with closing this one?

**Comment by danguita** [comment] 2016-12-14 15:43
I'm closing this one in the meantime!

**Closed as completed by danguita** 2016-12-14 15:43 UTC
Labels: bug, gobierto-consultations
