### ISSUE TITLE
Add IBM Notes credentials to Gobierto People configuration screen

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#627] opened 2017-04-18 13:07 UTC
Right now, IBM Notes credentials are stared as GobiertoPeople::Setting. Move these credentials to the new GobiertoModuleSettings module, and add the proper controls to the GobiertoPeople > Configuration page.

After this issue has been completed, we should review if GobiertoPeople::Setting is used elsewhere and remove the model, the fixtures and the table.

**Comment by amiedes** [comment] 2017-04-24 12:01
Working on this issue I noticed an "edge case" which I consider important to solve. In the `GobiertoPeople::IbmNotes::CalendarIntegration#sync_person_events` method, after making the API call to get the events, we mark as *pending* all the future events which are still present in our DB but which are not being returned any more by the API, thinking that it's because they have been deleted from the IBM Notes GUI.

```ruby
# app/services/gobierto_people/ibm_notes/calendar_integration.rb
def self.sync_person_events(person)

  # ...

  received_events_ids = received_events.map { |event| event['id'] }

  person.events.synchronized_future_events.each do |future_event|
    unless received_events_ids.include?(future_event.external_id)
      future_event.pending!
    end
  end
end
```

But if the service is unaivailable or because the credentials are incorrect, the api call will return an empty array: 

```ruby
def self.get_person_events(params)
  response_page = make_request(params)
  begin
    JSON.parse(response_page.body)["events"]
  rescue JSON::ParserError
    []
  end
end
```

**causing all future events of this site to be marked as pending in our DB.**

The problem is that given how the authentication to the API works (using Mechanize), it's not very clear how to differentiate between the cases where the credentials are wrong, the service is down or there are no events (I think in this case a blank HTML page is rendered instead of returning an empty array of events in the JSON data).

Also, when credentials are incorrect, the HTTP response status code is `200`, so it's not possible to use status codes to reason about the result of the request.

One way to solve this is to make this distinction by using Mechanize again to parse the returned page and see if a blank page is returned or we've been redirected to the login form again (a "wrong credentials" message is displayed in this case). The problem with this approach is that it's *very specific* to the site using IBM Notes calendar integration.

Any advice on this, @ferblape ?

**Comment by ferblape** [comment] 2017-04-25 05:36
Good catch @amiedes! You are totally right, and we need to deal with those exceptions.

There are two scenarios we need to detect:

1. invalid credentials
2. invalid response body

This is what I suggest for the `IbmNotes::Api` class:

```ruby
module IbmNotes
  class InvalidCredentials < StandardError; end
  class InvalidResponseBody < StandardError; end

  class Api

    def self.get_person_events(params)
      response_page = make_request(params)
      if response_page.uri.path == URI.parse(params[:endpoint]).path
        JSON.parse(response_page.body)["events"]
      else
        raise IbmNotes::InvalidCredentials
      end
    rescue JSON::ParserError
      raise IbmNotes::InvalidResponseBody
    end
...
```

- When (1) happens the `response_page.uri` is not the `endpoint` uri but the login page. 
- When (2) happens the JSON can't be parsed

Now, in `GobiertoPeople::IbmNotes::CalendarIntegration.sync_person_events(person)` method you need to capture these exceptions and don't process the events, but log the exceptions in the logger. Something like this:

```ruby
module GobiertoPeople
  module IbmNotes
    class CalendarIntegration

      def self.sync_person_events(person)
        received_events = ::IbmNotes::Api.get_person_events(request_params(person))

        received_events.each do |event_hash|
          event = ::IbmNotes::PersonEvent.new(person, event_hash)
          sync_event(event)
        end

        received_events_ids = received_events.map { |event| event['id'] }

        person.events.synchronized_future_events.each do |future_event|
          unless received_events_ids.include?(future_event.external_id)
            future_event.pending!
          end
        end
      rescue IbmNotes::InvalidCredentials
        Rails.logger.info "[#{person.site.name} calendar integration] Invalid credentials for site"
      rescue bmNotes::InvalidResponseBody
        Rails.logger.info "[#{person.site.name} calendar integration] Invalid JSON response for person #{person.id}"
      end
...
```

If you are OK with the changes, apply them to the PR, otherwise we can discuss in this thread.

**Comment by amiedes** [comment] 2017-04-25 07:11
I think this will solve the problem. I'll apply the changes, record some cassettes for the tests and apply them to the PR. Thanks!

**Comment by amiedes** [comment] 2017-04-26 10:36
I've found another edge case I wasn't sure how to handle:

* When there are no events
* When there is a (real) JSON parse error

When there are no events, a blank HTML page will be returned by the API call. So a JSON parse error will be thrown in both situations.

You can emulate this by appending the following query params to any of the endpoints we have: `?since=2013-07-01T00:00:00Z&before=2013-07-31T00:00:00Z` (for example).

In both cases the response_page uri is the original endpoint, so we can't use that strategy in this case.

I've decide to split the cases by checking the returned_page body like so: `response_page.body == ""`

```ruby
def self.get_person_events(params)
  response_page = make_request(params)
  begin
    if response_page.uri.path == URI.parse(params[:endpoint]).path
      if response_page.code.to_i == 200
        JSON.parse(response_page.body)["events"]
      else
        raise IbmNotes::ServiceUnavailable
      end
    else
      raise IbmNotes::InvalidCredentials
    end
  rescue JSON::ParserError
    if response_page.body == ""
      []
    else
      raise JSON::ParserError
    end
  end
end
```

This will fail the day there are events in IBM Notes and there is an error and they decide to return a blank page, but I think it's the closest we can get.

**Comment by ferblape** [comment] 2017-04-27 05:43
Sounds reasonable

**Closed as completed** 2017-04-27 17:28 UTC
